### ISSUE TITLE
Possible error in the implementation of CAGrad

### ISSUE THREAD

**Issue by yifei-he** [AvivNavon/nash-mtl#16] opened 2023-09-05 02:35 UTC
Thank you so much for the great work and for putting the code for all MTL algorithms together in a unified manner. 

I find a minor error in your implementation of CAGrad. From line 563-567 in methods/weight_methods.py, I suppose what you want to do is to retain the computation graph for all tasks except the last one so that some memory can be saved.  However, it seems that in the current implementation, the code will always go inside the first if statement, meaning that the computation graph is retained for all tasks. I find this issue because I run into out-of-memory errors when using your code. Hope this helps!

**Comment by AvivNavon** [comment] 2023-09-05 18:11
Thank you @yifei-he . The issue is now fixed.

**Closed as completed** 2023-09-05 18:11 UTC
